# File: air.toml
root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"                        # binary output
  cmd = "go build -o tmp/main ./cmd/web" # path ke folder, bukan file .go
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "air-errors.log"
  stop_on_error = true
  send_interrupt = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
